import { Question } from '../entities/question';

export const QUESTIONS: Question[] = [
  { questionId: 11,
    questionText: 'What is Inheritance?',
    sampleAnswer1: 'Money from dead relatives',
    sampleAnswer2: 'Genes I got from my parents',
    sampleAnswer3: 'A Bear can inherit from an Animal',
    sampleAnswer4: 'Inheritance is a way to reuse code',
    sampleAnswer5: 'The class which is inherited from, is called the base class,' +
      'and the class which inherits the code from the base class is called a derived class.',
    isActive: true,
    bucketId: 1
  },
  { questionId: 12,
    questionText: 'What is Polymorphism?',
    sampleAnswer1: 'Many forms',
    sampleAnswer2: 'Overloading and Overriding',
    sampleAnswer3: 'A child can be casted as a parent',
    sampleAnswer4: 'A parent object can be a child at runtime',
    sampleAnswer5: 'It is a feature, which lets us create functions with same name but different arguments, which will perform differently',
    isActive: true,
    bucketId: 1
  },
  { questionId: 13,
    questionText: 'What is Abstraction?',
    sampleAnswer1: 'An abstract action.',
    sampleAnswer2: 'Things are not known.',
    sampleAnswer3: 'Details are hidden.',
    sampleAnswer4: 'Hiding implementation details.',
    sampleAnswer5: 'Hiding implementation details and exposing only necessary functionality.',
    isActive: true,
    bucketId: 1
  },
  { questionId: 14,
    questionText: 'What is Encapsulation?',
    sampleAnswer1: 'A time machine.',
    sampleAnswer2: 'Something inside a capsule.',
    sampleAnswer3: 'Things are hidden.',
    sampleAnswer4: 'Hiding of details to prevent user access.',
    sampleAnswer5: 'Concealment of details using access modifiers such as private and protected.',
    isActive: true,
    bucketId: 2
  },
  { questionId: 15,
    questionText: 'What is a JOIN statement?',
    sampleAnswer1: 'Two statements together.',
    sampleAnswer2: 'Not a UNION statement.',
    sampleAnswer3: 'Connecting two tables.',
    sampleAnswer4: 'Joining two tables together in a SQL statement.',
    sampleAnswer5: 'Matching two tables based off of a common column.',
    isActive: true,
    bucketId: 2
  },
  { questionId: 16,
    questionText: 'What is the difference between a stored procedure and a function?',
    sampleAnswer1: 'Nothing.',
    sampleAnswer2: 'A stored procedure stores things and a function has a function.',
    sampleAnswer3: 'A stored procedure has no return and a function does.',
    sampleAnswer4: 'A stored procedure does not return anything and a function must return one thing and one thing only.',
    sampleAnswer5: 'A stored procedure does not have a return though it allows for multiple ' +
      'IN, OUT, and IN/OUT parameters and can be used for DML.  ' +
      'A function must return one thing and one thing only and cannot have DML.',
    isActive: true,
    bucketId: 3
  },
  { questionId: 17,
    questionText: 'What are the sublanguages of SQL?',
    sampleAnswer1: 'There are none.',
    sampleAnswer2: 'I know DML is one.',
    sampleAnswer3: 'DML, DQL and stuff.',
    sampleAnswer4: 'Data Definition Language, Data Manipulation Language, Data Query Language, and others.',
    sampleAnswer5: 'DDL Data Definition Language, DML Data Manipulation Language, DQL Data Query Language, ' +
      'DCL Data Control Language, and TCL Transaction Control Language',
    isActive: true,
    bucketId: 4
  },
  { questionId: 18,
    questionText: 'What are some clauses in SQL?',
    sampleAnswer1: 'Santa Claus.',
    sampleAnswer2: 'There are a few clauses but SELECT is all I know.',
    sampleAnswer3: 'There is SELECT and FROM.',
    sampleAnswer4: 'SELECT, FROM, and WHERE.',
    sampleAnswer5: 'SELECT, FROM, WHERE/HAVING, GROUP BY/ORDER BY',
    isActive: true,
    bucketId: 5
  },
  { questionId: 19,
    questionText: 'What does HTML stand for?',
    sampleAnswer1: 'HTML stands for HTML',
    sampleAnswer2: 'HTML is some kind of language.',
    sampleAnswer3: 'HTML stands for something, something markup language.',
    sampleAnswer4: 'Hype Text Markup Language.',
    sampleAnswer5: 'Hyper-Text Markup Language.',
    isActive: true,
    bucketId: 6
  },
  { questionId: 20,
    questionText: 'What is the first element of a HTML document?',
    sampleAnswer1: 'Hydrogen',
    sampleAnswer2: 'HTML',
    sampleAnswer3: 'TYPE',
    sampleAnswer4: 'DocumentType',
    sampleAnswer5: '!DOCTYPE',
    isActive: true,
    bucketId: 7
  },
  { questionId: 21,
    questionText: 'Name some HTML tags and explain them.',
    sampleAnswer1: 'I have no idea.',
    sampleAnswer2: 'There is <HTML>',
    sampleAnswer3: 'There is <HTML>, <head>, <body>',
    sampleAnswer4: '<HTML>, <head> provides metadata, <body>',
    sampleAnswer5: '<head> provides metadata, <body> the body of the document, <br> provides a single line break, ' +
      '<button> creates a clickable button',
    isActive: true,
    bucketId: 7
  },

];
