import {Bucket} from '../entities/bucket';

export const BUCKETS: Bucket[] = [
    { bucketId: 1,
      bucketCategory: 'Basic Java',
      bucketDescription: 'OCA level Java questions',
      isActive: true,
    },
    { bucketId: 2,
      bucketCategory: 'SQL',
      bucketDescription: 'SQL database questions',
      isActive: true,
    },
    { bucketId: 3,
      bucketCategory: 'JavaScript',
      bucketDescription: 'JavaScript questions',
      isActive: true,
    },
    { bucketId: 4,
      bucketCategory: 'HTML',
      bucketDescription: 'JavaScript questions',
      isActive: true,
    },
    { bucketId: 5,
      bucketCategory: 'CSS',
      bucketDescription: 'JavaScript questions',
      isActive: true,
    },
    { bucketId: 6,
      bucketCategory: 'Spring',
      bucketDescription: 'JavaScript questions',
      isActive: true,
    },
    { bucketId: 7,
      bucketCategory: 'Angular',
      bucketDescription: 'JavaScript questions',
      isActive: true,
    }
  ];